#!/bin/bash
echo "    )             (     "
echo " ( /(     (       )\ )  "
echo " )\())    )\     (()/(  "
echo "((_)\   (((_)     /(_)) "
echo " _((_)  )\___    (_))_| "
echo "| || | ((/ __|   | |_   "
echo "| __ | _| (__  _ | __|  "
echo "|_||_|(_)\___|(_)|_|    "
echo "  Halt and Catch Fire   "
echo ""
